#server:
#    port: 8763
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: provider #主机别名
#
#spring:
#  application:
#    name: provider
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server
#      profile: dev
#env: dev
